== Fardjad's dotfiles

=== Synopsis

This repository contains my no-frills 
https://wiki.archlinux.org/title/Dotfiles[dotfiles]. 
I use these dotfiles on the latest version of 
https://www.apple.com/macos[macOS] and https://ubuntu.com/wsl[Ubuntu on WSL].

It comes with an automated installer script and leverages 
https://brew.sh[homebrew] to install packages on macOS and various Linux 
distributions.

=== Included Tools

list-tools::[]

=== Installation

The following software packages are required to run the setup script.

[cols="1,4" options="header"]
|===
|Dependency
|Purpose

|https://git-scm.com[git]
|Required for cloning this repository

|https://curl.haxx.se[curl]
|Used for downloading files from the web

|https://www.gnu.org/software/bash[bash]
|Required for running the installer script

|https://brew.sh[brew]
|Required for installing packages on macOS or Linux

|https://www.sudo.ws[sudo]
|Required by the installer script to run some commands as root
|===

Make sure the dependencies are installed, and clone the repository:

[source,bash]
....
git clone https://github.com/fardjad/dotfiles.git ~/.dotfiles
....

==== Install Everything

You can choose to install all of the tools by running the following command:

[source,bash]
....
~/.dotfiles/script/setup
....

==== Install Individual Tools

If you don't want to install everything, you can run the installer script of 
each tool individually. For example, to install `nodejs`, you can run:

[source,bash]
....
~/.dotfiles/nodejs/install.sh
....

Keep in mind that these dotfiles are designed to work with zsh, so it's highly 
recommended that you install zsh too:

[source,bash]
....
~/.dotfiles/zsh/install.sh
....

Running the installer scripts multiple times is safe, and in most cases it will 
update the installed packages to the latest version.

=== OS Specific Notes

* (macOS only, optional) In order to set macOS defaults run the following:

[source,bash]
....
[ -d ~/.dotfiles ] && ~/.dotfiles/macos/setup-macos.sh || echo >&2 'You must clone the repository first!'
....

* (macOS only, optional) Configure iTerm2 to load preferences from 
`~/.dotfiles/macos/iterm2` directory.

* (macOS only, Apple Silicon) Run the following to enable Rosetta:

[source, bash]
....
softwareupdate --install-rosetta
....

=== Credits

The directory structure of this repository is inspired by 
https://github.com/caarlos0/dotfiles[carlos' dotfiles]
