[tools]
go = "latest"
kubectl = "latest"
[tools."github:helm/helm"]
version = "latest"
bin_path = '{{os(macos="darwin")}}-{{arch(x64="amd64", arm64="arm64")}}'
[tools."github:helm/helm".platforms]
macos-arm64 = { url = "https://get.helm.sh/helm-v{{ version }}-darwin-arm64.tar.gz", bin_path = "darwin-arm64" }
macos-x64 = { url = "https://get.helm.sh/helm-v{{ version }}-darwin-amd64.tar.gz", bin_path = "darwin-amd64" }
linux-arm64 = { url = "https://get.helm.sh/helm-v{{ version }}-linux-arm64.tar.gz", bin_path = "linux-arm64" }
linux-x64 = { url = "https://get.helm.sh/helm-v{{ version }}-linux-amd64.tar.gz", bin_path = "linux-amd64" }

[tool_alias]
docker = "aqua:docker/cli"
docker-compose = "github:docker/compose"
docker-buildx = "github:docker/buildx"
kubectx = "github:ahmetb/kubectx"
kubens = "github:ahmetb/kubectx"

[tools.docker]
version = "latest"

[tools.docker-compose]
version = "latest"
asset_pattern = 'docker-compose-{{os(macos="darwin")}}-{{arch(x64="x86_64", arm64="aarch64")}}'
bin = "docker-compose"

[tools.docker-buildx]
version = "latest"
asset_pattern = 'buildx-v{{version}}.{{os(macos="darwin")}}-{{arch(x64="amd64")}}'
bin = "docker-buildx"

[tools.kubectx]
version = "latest"
matching_regex = "^kubectx_v"
rename_exe = "kubectx"

[tools.kubens]
version = "latest"
matching_regex = "^kubens_v"
rename_exe = "kubens"
