#!/bin/bash

if ! command -v rsync 2>&1 >/dev/null; then
  echo 'rsync is not installed!'
  exit 1
fi

if [ "$#" -ne 2 ]; then
    echo "Usage: tgz-node-project /path/to/node/project /path/to/backup/archive.tar.gz"
    exit 1
fi

if [ ! -d "$1" ]; then
  echo "$1 is not a directory!"
  exit 1
fi

if [ -e "$2" ]; then
  echo "$2 already exists!"
  exit 1
fi

tmp_dir=$(mktemp -d)
rsync -avz --exclude 'node_modules' "${1%/}/" "${tmp_dir%/}/"
tar -czf "$2" -C "${tmp_dir}" .
rm -rf "${tmp_dir}"
