#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

ROOT="$(dirname "$0")/.."
DIR="$PWD"
cd "$ROOT"
if [ -f .commit ]; then
    rm .commit

    # TODO: run commands and add stage changes
    git commit --amend -C HEAD --no-verify
fi
cd "$DIR"
