#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

ROOT="$(dirname "$0")/.."
DIR="$PWD"
cd "$ROOT"
if [ -f .commit ]; then
    rm .commit

    npm run ascaid:gfm
    npx prettier -w ./docs
    git add docs
    git commit --amend -C HEAD --no-verify
fi
cd "$DIR"
